### ISSUE TITLE
Running npm test fails

### ISSUE THREAD

**Issue by mheadd** [NuAxis/samwise#4]
Running ```npm test```  throws an error:

```
Configuration for rule "comma-dangle" is invalid:
Severity should be one of the following: 0 = off, 1 = warning, 2 = error (you passed "error").
```

Seems like the ```.eslintrc.json``` file is not formatted properly..?

**Comment by Faheemitian** [comment]
Thank you for reporting. 

It's not a configuration issue but missing dependency. Just committed a fix. Please pull and verify when you have time.

**Comment by mheadd** [comment]
Yes, that fixed it. Thanks!
